### ISSUE TITLE
Realtime prediction

### ISSUE THREAD

**Issue by Zumbalamambo** [njoye/CNN-Tracker-v2#1]
so How do I run this code for realtime prediction?

**Comment by njoye** [comment]
Hi @Zumbalamambo, I'm currently not working on this project anymore since I was building it (partially) for a company. Still the code should be able to run in realtime, but there are some (exactly 3) limiting factors! Also note that the YOLO functionality has not been built in yet (which isn't really hard though, you just take YOLO, alter the code to return the coordinates and mark them in py-MDNet for tracking, add some heatmapping or stuff to check if the given object is already being tracked - that was my plan).

1. py-mdnet (object tracking)
2. YOLO (object recognition)
3. your hardware

I. py-MDNet
MDNet is eating your resources as if they were a Cheese-Burger in McDonalds, so be aware of that. What I did to increase the tracking speed was that I tried only giving it a third or half of the frames (meaning every second or every third frame). This was yielding good results and after implementing the emergency mode I was able to even recover after a full occlusion with 1/2 of the frames. 1/3 or less is good if you're not expecting any full or only partial occlusions. What you could also try is giving MDNet the full amount of the frames for about 10% of the total frames (because it starts to get to know the object really well there) and then later on cut some of the frames off.

II. YOLO
There are many suggestions on the internet about how to make YOLO faster, the easiest one I can think of is simply using Tiny-YOLO instead of the full fletched weights and config. Just google around a bit, you'll probably find some stuff.

III. Your Hardware
This one is INCREDIBLY IMPORTANT! If you're not able to run either YOLO or MDNet itself in realtime on your hardware, you'll not be able to run this software in realtime, as it is basically a Frankenstein of both systems. You're running to CNN's at the same time! I was using a Titan Xp and a i7 8xxx (don't remember) with 32GB of RAM and even on that PC I had to cut off some of the frames to get it running in real time. If you're way below these requirements or don't have a graphics card at all, I would recommend you don't even attempt it.

Final notes: 
This is not a system for realtime "prediction", all i'm doing there is stitching together object recognition and object tracking to get a proper system. Codewise, this project is not at all(!!) finished, so if you run into any bugs or have any other questions, just open another Issue and I'll take a look at it. 

I will start my work on this project eventually again, but for now I am really busy and can't properly maintain, nor develop it further.
